[package]
name = "rslack"
version = "0.1.0"
authors = ["Kohei Sugimoto <18735471+kohbis@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
libc = "0.2"
reqwest = { version = "0.10.8", features = ["json"] }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
tokio = { version = "0.2.22", features = ["full"] }
url = "2.1.1"

[dev-dependencies]
serial_test = "0.5.0"
