[package]
name = "rslack"
version = "0.5.2"
authors = ["kohbis <dev.kohbis@gmail.com>"]
edition = "2021"
description = "cli for posting slack message"
readme = "README.md"
license = "MIT"
repository = "https://github.com/kohbis/rslack"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.99"
dirs = "6.0"
libc = "0.2"
reqwest = { version = "0.12.23", features = ["json"] }
rpos = "0.3.0"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
structopt = "0.3.20"
termion = "4.0.5"
tokio = { version = "1.45.1", features = ["full"] }
unicode-width = "0.2.1"
url = "2.5.7"

[dev-dependencies]
mockito = "1.7.0"
serial_test = "3.2.0"
