[package]
name = "rslack"
version = "0.2.1"
authors = ["kohbis <dev.kohbis@gmail.com>"]
edition = "2021"
description = "cli for posting slack message"
readme = "README.md"
license = "MIT"
repository = "https://github.com/kohbis/rslack"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
libc = "0.2"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
structopt = "0.3.20"
termion = "1.5.6"
tokio = { version = "1.20.1", features = ["full"] }
unicode-width = "0.1.7"
url = "2.1.1"

[dev-dependencies]
serial_test = "0.9.0"

