[package]
name = "rslack"
version = "0.2.4"
authors = ["kohbis <dev.kohbis@gmail.com>"]
edition = "2021"
description = "cli for posting slack message"
readme = "README.md"
license = "MIT"
repository = "https://github.com/kohbis/rslack"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
libc = "0.2"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
structopt = "0.3.20"
termion = "2.0.1"
tokio = { version = "1.23.0", features = ["full"] }
unicode-width = "0.1.10"
url = "2.3.1"

[dev-dependencies]
serial_test = "0.10.0"

