[package]
name = "rslack"
version = "0.4.0"
authors = ["kohbis <dev.kohbis@gmail.com>"]
edition = "2021"
description = "cli for posting slack message"
readme = "README.md"
license = "MIT"
repository = "https://github.com/kohbis/rslack"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
dirs = "5.0"
libc = "0.2"
reqwest = { version = "0.11.23", features = ["json"] }
rpos = "0.3.0"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.110"
structopt = "0.3.20"
termion = "2.0.3"
tokio = { version = "1.35.1", features = ["full"] }
unicode-width = "0.1.11"
url = "2.5.0"

[dev-dependencies]
mockito = "1.2.0"
serial_test = "2.0.0"
